-- PODSTAWOWE ZAPYTANIA 
-- 1.WYPISANIE KUCHARZY KTORZY MAJA DOSWIADCZENIE POWYZEJ 10 LAT
SELECT IMIE, NAZWISKO 
FROM KUCHARZ 
WHERE DOSWIADCZENIE > 10;

-- 2. WYPISANIE IMION I NAZWISKO WSZYSTKICH KLIENTOW
SELECT IMIE, NAZWISKO
FROM KLIENT;

-- 3. WYPISANIE ZAMOWIEN KTORYCH DATA JEST W LIPCU
SELECT DATA_ZAMOWIENIA
FROM ZAMOWIENIE
WHERE EXTRACT(MONTH FROM DATA_ZAMOWIENIA) = '7' ;

-- ZAPYTANIA ZAWIERAJACE ZLACZENIA

-- 4. WYPISANIE IMIONA POMOCNIKOW KTORZY POMAGAJA KUCHARZOWI WRAZ Z IMIONAMI KUCHARZY
SELECT KUCHARZ.IMIE KUCHARZ, POMOCNIK.IMIE POMOCNIK
FROM POMOCNIK
INNER JOIN KUCHARZ ON KUCHARZ.ID_KUCHARZ = POMOCNIK.ID_KUCHARZ;

-- 5. WYPISANIE ZAMOWIEN KTORE KELNER PRZYGOTOWAL DLA KLIENTA
SELECT KLIENT.IMIE KLIENT, KELNER.IMIE KLENER, ZAMOWIENIE.ID_ZAMOWIENIA
FROM ZAMOWIENIE
INNER JOIN KLIENT ON ZAMOWIENIE.ID_KLIENT = KLIENT.ID_KLIENT
INNER JOIN KELNER ON ZAMOWIENIE.ID_KELNER = KELNER.ID_KELNER;

-- 6. WYPISANIE DOSTAWCY KTORY DOSTARCZYL ZAMOWIENIE Z PODANIEM CENY DANEGO ZAMOWIENIA
SELECT ZAMOWIENIE.ID_ZAMOWIENIA, ZAMOWIENIE.KOSZT_ZAMOWIENIA, DOSTAWCA.IMIE
FROM ZAMOWIENIE
INNER JOIN DOSTAWCA ON ZAMOWIENIE.ID_DOSTAWCA = DOSTAWCA.ID_DOSTAWCA;


-- ZAPYTANIA ZAWIERAJACE GRUPOWANIE
-- 7. SORTOWANIE DATY ZATRUDNIENIA PRACOWNIKA ROSNACO WEDLUG MIESIECY
SELECT DATA_ZATRUDNIENIA, PRACOWNIK.IMIE
FROM PRACOWNIK
WHERE (EXTRACT(MONTH FROM DATA_ZATRUDNIENIA)) BETWEEN '5' AND '12'
ORDER BY (EXTRACT(MONTH FROM DATA_ZATRUDNIENIA));

-- 8. WYPISANIE ILU POMOCNIKOW POMAGA TEMU SAMEMU KUCHARZOWI
SELECT POMOCNIK.KUCHARZ_ID_KUCHARZ KUCHARZ, COUNT(*)
FROM POMOCNIK
INNER JOIN KUCHARZ ON POMOCNIK.ID_KUCHARZ = KUCHARZ.ID_KUCHARZ
GROUP BY POMOCNIK.ID_KUCHARZ
ORDER BY POMOCNIK.ID_KUCHARZ;

-- 9. WYPISANIE PRACOWNIKOW OD NAJWCZESNIEJ ZATRUDNIONEGO 
SELECT * FROM PRACOWNIK;
SELECT DATA_ZATRUDNIENIA
FROM PRACOWNIK
GROUP BY DATA_ZATRUDNIENIA;

-- ZAPYTANIA ZAWIERAJACE PODZAPYTANIA
-- 10. WYPISANIE POMOCNIKA I KUCHARZA KTORZY MAJA TYLE SAMO DOSWIADCZENIA
SELECT P.IMIE, P.NAZWISKO
FROM POMOCNIK P
WHERE P.ID_KUCHARZ IN (SELECT ID_KUCHARZ FROM KUCHARZ K WHERE K.DOSWIADCZENIE = P.DOSWIADCZENIE);


-- 11. WYPISANIE NAJWIEKSZEJ ILOSCI ZAMOWIEN DOSTARCZONYCH PRZEZ DANEGO DOSTAWCE
SELECT MAX (C) MAX
FROM (SELECT ID_DOSTAWCA, COUNT(*) C 
FROM ZAMOWIENIE
GROUP BY ID_DOSTAWCA);


-- 12. WYPISANIE PRACOWNIKA KTORY ZARABIA TYLE SAMO CO KUCHARZ
SELECT KUCHARZ.IMIE
FROM KUCHARZ
WHERE PENSJA = (SELECT PENSJA FROM PRACOWNIK WHERE KUCHARZ.ID_PRACOWNIK = PRACOWNIK.ID_PRACOWNIK);


